Develop
Ushlerdop/crt-todo pull request #1
Opened 2022-01-08 15:36 UTC by Ushlerdop

Создал две отдельных формы для создания и изменения задач. Добавил компоненты модального окна, в котором и изменяется задача. И кнопку для редактирования задачи. Модальное окно вызывается с помощью кнопки с карандашом у каждой задачи. Также покопался немного в стилях и добавил заготовку для ограничения текста в слишком больших задачах.
Изменил createdDate на editedDate. Теперь при создании и изменении будет отображаться 'Edited' и дата изменения. Также как и в Google Keep.

P.S. Извиняюсь за такой большой PR, по неопытности :( 
В следующий раз буду делать commit при меньших изменениях.

2022-01-11 09:00 UTC, BubbaCat reviewed
В целом все хорошо, молодец :)

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/Todo.jsx
> +      tasks: [
Если решил замокать данные, то лучше вынеси их в отдельный файл

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/Todo.jsx
> +      tasks: this.state.tasks.map(task => {
const tasks = this.state.tasks.map(task => { .....})
this.SetState({tasks});

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/Todo.jsx
> +      tasks: this.state.tasks.map(task => {
см. выше

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/Todo.jsx
> +      tasks: this.state.tasks.map(task => {
см. выше

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/TodoForms/TodoAddForm/TodoAddForm.jsx
> +    if ( e.target.title.value && e.target.description.value ) {
Лучше не делать вложенность if'ов
    if ( !(e.target.title.value && e.target.description.value) ) { 
          alert('You have to text something in Title and Description');
          return;
    } ну и потом уже следующий if написать

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/TodoForms/TodoAddForm/TodoAddForm.module.scss
> +    border-radius: inherit;
Лучше писать css стили в от в таком порядке 
1.Сначала положение элемента относительно других
2. Затем размеры и отступы
3.Рамка border, она частично относится к размерам
4.Общее оформление содержимого
5.Цветовое и стилевое оформление

так легче читать и расширять, но это просто заметка на будущее, можно поставить npm пакет, которые это будет делать за нас в одном команду

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Modal/Modal.jsx
> +    }
?

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Modal/Modal.jsx
> +          className={this.props.active ? styles.modal + ' ' + styles.active : styles.modal}
\` ${styles.modal} ${styles.active} `

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Modal/Modal.jsx
> +            className={this.props.active ? styles.modalContent + ' ' + styles.active : styles.modalContent}
см выше

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/TodoList/TodoList.jsx
> +            <TodoTask
т.к у тебя поля совпадают поля пропсов совпадают с названиями полей класса то можно
<TodoTask
key={task.id}
{...task}
/>
js позволяет не писать одинаковые поля для объектов : 
{
tast: task,
id: id,
} 
тоже самое что и(при условия, что те поля не undefined)
{
task,
id
}

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Modal/Modal.jsx
> +          className={this.props.active ? styles.modal + ' ' + styles.active : styles.modal}
У тебя же classNames подключен, используй его для таких условий

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/TodoTask/TodoTask.jsx
> +          updateTask={this.props.updateTask}
{...this.props}

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/TodoTask/TodoTask.jsx
> +          {...this.props}
можешь ведь, когда захочешь :)

2022-01-11 09:00 UTC, BubbaCat commented on src/components/Todo/TodoTask/TodoTaskModal.jsx
> +          updateTask={this.props.updateTask}
см выше

2022-01-11 10:09 UTC, BubbaCat requested changes

2022-01-11 10:09 UTC, BubbaCat commented on src/components/Todo/TodoMods/TodoMods.jsx
> +    let DoneTasksClassName = cx({
const

2022-01-11 10:09 UTC, BubbaCat commented on src/components/Todo/TodoMods/TodoMods.jsx
> +    let ImportantTasksClassName = cx({
const и в езде используй const

2022-01-11 10:09 UTC, BubbaCat commented on src/components/Todo/TodoTask/TodoTask.jsx
> +let cx = classNames.bind(styles);
const

2022-01-11 10:09 UTC, BubbaCat commented on src/components/Todo/TodoTask/TodoTaskModal.jsx
> +    let titleTaskClassName = cx({
let на const во всех местах

2022-01-11 10:48 UTC, BubbaCat commented on src/components/Todo/Todo.jsx
> +    this.setState({
Ну на самом деле лучше в setState функцию (prevState)=> 
Чтобы не было потом, что у нас стейт ведет себя непредсказуемо.

2022-01-11 14:17 UTC, BubbaCat commented
Также доп замечания  от Михаила  написаны в телеграм

2022-01-12 07:40 UTC, Ushlerdop commented on src/components/Todo/TodoTask/TodoTask.jsx
> +          updateTask={this.props.updateTask}
В пропсах находятся методы, которые не используются в этом компоненте. Или ради читаемости кода можно передать немного лишнего в компонент?

2022-01-18 08:08 UTC, merged